spring.application.name=Formulaire-RI2S

# --- CONFIGURATION PORT (CRUCIAL POUR RENDER) ---
server.port=${PORT:8080}

# --- CONFIGURATION BASE DE DONNÉES ---
# On utilise la variable d'environnement que tu vas créer sur Render
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Console et Logs
spring.h2.console.enabled=false
spring.jpa.show-sql=true
spring.sql.init.mode=always